name: Simple Commands
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Echo
        run: echo "Hello world"
      - name: Run Date
        run: date
      - name: Run LS
        run: ls -la
